export { PreclaimClient } from './client.js';
export { cliCommands, mcpTools, hooks, configEntries, getCommandDescription, getToolDescription } from './docs.js';
export type { DocCommand, DocCommandOption, DocTool, DocToolArg, DocHook, DocConfigEntry } from './docs.js';
export { findConfig, loadCredentials, getCredentialsPath, defaultConfig, getSupabaseConfig, saveCredentials, refreshCredentials } from './config.js';
export type {
  ActivityEntry,
  Organization,
  Profile,
  Project,
  Session,
  SessionWithProfile,
  Lock,
  LockHolder,
  LockHistoryEntry,
  FileInterest,
  RegisterInterestRequest,
  CheckInterestsRequest,
  CheckInterestsResult,
  ClaimStatus,
  ClaimResult,
  ClaimRequest,
  BatchCheckRequest,
  BatchCheckResult,
  HeartbeatRequest,
  HeartbeatResult,
  SessionRegisterRequest,
  ReleaseRequest,
  ReleaseResult,
  StatsResult,
  PreclaimConfig,
  PreclaimCredentials,
  ApiResponse,
  HookInput,
  HookResult,
  MeResult,
  VersionResult,
} from './types.js';
